# Generated by Django 4.2.7 on 2023-11-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookMetaNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'facebook',
            },
        ),
        migrations.CreateModel(
            name='TwitterXNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_x_url', models.URLField(verbose_name='X')),
            ],
            options={
                'verbose_name': 'X',
            },
        ),
    ]
