# Generated by Django 4.2.7 on 2023-11-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookmetanetwork',
            options={'verbose_name': 'facebook', 'verbose_name_plural': 'facebook'},
        ),
        migrations.AlterModelOptions(
            name='twitterxnetwork',
            options={'verbose_name': 'X', 'verbose_name_plural': 'X'},
        ),
    ]
