# Generated by Django 4.2.5 on 2023-11-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_facebookmetanetwork_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookMetaNetwork',
        ),
        migrations.DeleteModel(
            name='TwitterXNetwork',
        ),
    ]
