# Generated by Django 4.2.7 on 2023-11-05 03:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('newrecipes', django.db.models.manager.Manager()),
            ],
        ),
    ]
